cc_library(
	name = "mod",
	srcs = ["my_hashmap.hpp"],
	visibility = ["//lexer:__pkg__"],
	copts = [ "-I/usr/include/c++/11", "-I/usr/include/x86_64-linux-gnu/c++/11"],
	includes = [ "/usr/include/c++/11", "/usr/include/x86_64-linux-gnu/c++/11"]
)