cc_library(
	name="lexer",
	srcs= ["lexer.cpp"],
	hdrs= ["lexer.hpp"],
	visibility = ["//compiler:__pkg__"],
	deps = ["//modules:mod", "//utils:utils"],
	copts = [ "-I/usr/include/c++/11", "-I/usr/include/x86_64-linux-gnu/c++/11"],
	includes = [ "/usr/include/c++/11", "/usr/include/x86_64-linux-gnu/c++/11"]
)