cc_library(
	name = "Find",
	srcs = ["Find.cpp"],
	hdrs = ["Find.hpp"],
	visibility = [
		"//lexer:__pkg__",
		"//main:__pkg__",
	]
)
cc_library(
	name = "Errors",
	srcs = ["Errors.cpp"],
	hdrs = ["Errors.hpp"],
	visibility = [
		"//lexer:__pkg__",
		"//main:__pkg__",
	]
)
cc_library(
	name = "Trim",
	srcs = ["Trim.cpp"],
	hdrs = ["Trim.hpp"],
	visibility = [
		"//lexer:__pkg__"
	],
)