cc_library(
	name="utils",
	srcs= ["Errors.cpp", "Find.cpp"],
	hdrs= ["Errors.hpp", "Find.hpp"],
	visibility = ["//lexer:__pkg__", "//compiler:__pkg__"],
	copts = [ "-I/usr/include/c++/11", "-I/usr/include/x86_64-linux-gnu/c++/11"],
	includes = [ "/usr/include/c++/11", "/usr/include/x86_64-linux-gnu/c++/11"]
)